using System;
using Newtonsoft.Json;

namespace Patreon.Net.Models
{
    /// <summary>
    /// A benefit added to the campaign, which can be added to a tier to be delivered to the patron.
    /// </summary>
    [PatreonResource("benefit")]
    public class Benefit
    {
        public class Relationships
        {
            /// <summary>
            /// The campaign the benefit belongs to.
            /// </summary>
            [JsonProperty("campaign")]
            public Campaign Campaign { get; set; }
            /// <summary>
            /// (Alpha) The campaign-app connection
            /// </summary>
            //[JsonProperty("campaign_installation")]
            //public object CampaignInstallation { get; set; }
            /// <summary>
            /// The deliverables that have been generated by the benefit.
            /// </summary>
            [JsonProperty("deliverables")]
            public ResourceArray<Deliverable, Deliverable.Relationships> Deliverables { get; set; }
            /// <summary>
            /// The tiers the benefit has been added to.
            /// </summary>
            [JsonProperty("tiers")]
            public ResourceArray<Tier, Tier.Relationships> Tiers { get; set; }
        }
        /// <summary>
        /// The third-party external ID this reward is associated with, if any. Can be <see langword="null"/>.
        /// </summary>
        [JsonProperty("app_external_id")]
        public string AppExternalId { get; set; }
        /// <summary>
        /// Any metadata the third-party app included with this benefit on creation. Can be <see langword="null"/>.
        /// </summary>
        [JsonProperty("app_meta")]
        public object AppMeta { get; set; }
        /// <summary>
        /// The type of benefit, such as "custom" for creator-defined benefits. Can be <see langword="null"/>.
        /// </summary>
        [JsonProperty("benefit_type")]
        public string BenefitType { get; set; }
        /// <summary>
        /// The time this benefit was created.
        /// </summary>
        [JsonProperty("created_at")]
        public DateTimeOffset CreatedAt { get; set; }
        /// <summary>
        /// The number of deliverables for this benefit that are due today specifically.
        /// </summary>
        [JsonProperty("deliverables_due_today_count")]
        public int DeliverablesDueTodayCount { get; set; }
        /// <summary>
        /// The number of deliverables for this benefit that have been marked complete.
        /// </summary>
        [JsonProperty("delivered_deliverables_count")]
        public int DeliveredDeliverablesCount { get; set; }
        /// <summary>
        /// The benefit display description. Can be <see langword="null"/>.
        /// </summary>
        [JsonProperty("description")]
        public string Description { get; set; }
        /// <summary>
        /// Whether or not this benefit has been deleted.
        /// </summary>
        [JsonProperty("is_deleted")]
        public bool IsDeleted { get; set; }
        /// <summary>
        /// Whether or not this benefit is no longer available to new patrons
        /// </summary>
        [JsonProperty("is_ended")]
        public bool IsEnded { get; set; }
        /// <summary>
        /// Whether or not this benefit is ready to be fulfilled to patrons.
        /// </summary>
        [JsonProperty("is_published")]
        public bool IsPublished { get; set; }
        /// <summary>
        /// The next due date (after EOD today) for this benefit. Can be <see langword="null"/>.
        /// </summary>
        [JsonProperty("next_deliverable_due_date")]
        public DateTimeOffset? NextDeliverableDueDate { get; set; }
        /// <summary>
        /// The number of deliverables for this benefit that are due, for all dates.
        /// </summary>
        [JsonProperty("not_delivered_deliverables_count")]
        public int NotDeliveredDeliverablesCount { get; set; }
        /// <summary>
        /// A rule type designation, such as "eom_monthly" or "one_time_immediate". Can be <see langword="null"/>.
        /// </summary>
        [JsonProperty("rule_type")]
        public string RuleType { get; set; }
        /// <summary>
        /// The number of tiers containing this benefit.
        /// </summary>
        [JsonProperty("tiers_count")]
        public int TiersCount { get; set; }
        /// <summary>
        /// The benefit display title.
        /// </summary>
        [JsonProperty("title")]
        public string Title { get; set; }
    }
}
